### ISSUE TITLE
random

### ISSUE THREAD

**Issue by Arkveles** [Volodyaid/Starter_to_BitCrack_All_66pazl#1]

**Comment by Volodyaid** [comment]
Hi. my script performs the task of traversing the sections of the range specified in the text file. In the example you wrote, there are spaces after 1 and 3, which is not correct. 11.10.2023, 15:34, "Akveles" ***@***.***>: Good afternoon! I can't figure out why the range is split. Will the code work correctly if I just specify 1 FFFFFFFFFFFFFFFF:3 FFFFFFFFFFFFFFFF for 66 puzzle—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>  -- С уважением

**Comment by Arkveles** [comment]
Thank you for the answer!
